#ifndef CONTROLLERS_NETWORK_CODES_H_
#define CONTROLLERS_NETWORK_CODES_H_

// NC == Network Code

#define NC_CLIENT_PLAYER_ADDED 7
#define NC_CLIENT_VOTING_INFO 8
#define NC_HOST_VOTING_INFO 9
#define NC_CLIENT_DONE_WITH_VOTE 10
#define NC_CLIENT_DONE_ACTIVATE_TERMINAL 11
#define NC_CLIENT_TERMINAL_DONE 256

#endif /* CONTROLLERS_NETWORK_CODES_H_ */
