#ifndef CONTROLLERS_NETWORK_CODES_H_
#define CONTROLLERS_NETWORK_CODES_H_

// NC == Network Code

#define NC_HOST_ALL_PLAYER_INFO 2
#define NC_CLIENT_ONE_PLAYER_INFO 4
#define NC_CLIENT_PLAYER_ADDED 7
#define NC_CLIENT_PLAYER_REMOVED 255
#define NC_CLIENT_VOTING_INFO 8
#define NC_HOST_VOTING_INFO 9
#define NC_CLIENT_DONE_WITH_VOTE 10
#define NC_CLIENT_DONE_ACTIVATE_TERMINAL 11
#define NC_CLIENT_TERMINAL_DONE 256
#define NC_CLIENT_CLEAR_VOTES 257
#define NC_CLIENT_CLEAR_DONE 258
#define NC_HOST_CHANGE_STAGE 259

#endif /* CONTROLLERS_NETWORK_CODES_H_ */
