#ifndef CONTROLLERS_NETWORK_CODES_H_
#define CONTROLLERS_NETWORK_CODES_H_

// NC == Network Code

#define NC_HOST_ALL_PLAYER_INFO 1
#define NC_HOST_PLAYER_BASIC_INFO 2
#define NC_CLIENT_BASIC_PLAYER_INFO 3
#define NC_CLIENT_ONE_PLAYER_INFO 4

#define NC_DEPOSIT_ENERGY 5
#define NC_DEPOSIT_ENERGY_SUCCESS 6
#define NC_TERMINAL_ENERGY_UPDATE 7

#define NC_HOST_ALL_ENEMY_POSITION_UPDATE 8
#define NC_HOST_ALL_ENEMY_OTHER_INFO_UPDATE 9

#define NC_CLIENT_ENEMY_HIT_INFO 10

#define NC_BETRAYAL_TARGET_INFO 11
#define NC_SEND_DISABLE_PLAYER_INFO 12
#define NC_SEND_BETRAYAL_CORRUPT_INFO 13

#endif /* CONTROLLERS_NETWORK_CODES_H_ */
